/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SwingRouteImport } from './routes/swing'
import { Route as IndexRouteImport } from './routes/index'

const SwingRoute = SwingRouteImport.update({
  id: '/swing',
  path: '/swing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/swing': typeof SwingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/swing': typeof SwingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/swing': typeof SwingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/swing'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/swing'
  id: '__root__' | '/' | '/swing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SwingRoute: typeof SwingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/swing': {
      id: '/swing'
      path: '/swing'
      fullPath: '/swing'
      preLoaderRoute: typeof SwingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SwingRoute: SwingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
